# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30edee304840f45d3231f339068c5d994073ff36822dc089790e19193febb7359af27d27d84c01ac28d786d1c456da1c0219c10abfc9c6b4825b341d405275f4

test:
  secret_key_base: 1e6b7108681262fea532c1d535774e91a53632fd05df57e1558c1ae22b66252cc6913445380bb2efcb00887ea7ded5c8ca39f705fb67dd51ef53ae54a487b132

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
